apiVersion: v1
kind: Service
metadata:
  name: nbiot-gateway-udp
spec:
  type: LoadBalancer
  ports:
  - port: 1812
    name: radius
    protocol: UDP
  - port: 41234
    name: udp-ctl
    protocol: UDP
  - port: 51000
    name: udp-data
    protocol: UDP
