apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nbiot-gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nbiot-gateway
    spec:
    spec:
      containers:
      - name: nbiot-gateway
        image: lucarv/nbiot-gateway
        ports:
        - containerPort: 6379
          name: redis    
      containers:
      - name: nbiot-gateway
        image: lucarv/nbiot-gateway
        ports:
        - containerPort: 443
          name: port443
        - containerPort: 8080
          name: port3000
        - containerPort: 1812
          name: radius
          protocol: UDP
        - containerPort: 41234
          name: udp-ctl
          protocol: UDP
        - containerPort: 51000
          name: udp-data
          protocol: UDP          